import type { ThemeConfig } from 'antd';

export const theme: ThemeConfig = {
  components: {
    Table: {
      headerBg: '#e5ebfd',
      borderColor: '#dbe4ff',
    },
  },
  token: {
    colorPrimary: '#588ac9',
    colorSuccess: '#6bcf7f',
    colorWarning: '#f3c677',
    colorError: '#e88c87',
    colorInfo: '#588ac9',
    colorTextBase: '#334155',
    colorBgBase: '#ffffff',
    colorPrimaryBg: '#eef2ff',
    colorPrimaryBgHover: '#dbe4ff',
    colorPrimaryBorder: '#bac8f3',
    colorPrimaryBorderHover: '#9bb0e6',
    colorPrimaryHover: '#3f6cb8',
    colorPrimaryActive: '#2e5aa8',
    colorPrimaryText: '#588ac9',
    colorPrimaryTextHover: '#3f6cb8',
    colorPrimaryTextActive: '#2e5aa8',
    colorSuccessBg: '#f0fdf4',
    colorSuccessBgHover: '#dcfce7',
    colorSuccessBorder: '#bbf7d0',
    colorSuccessBorderHover: '#86efac',
    colorSuccessHover: '#22c55e',
    colorSuccessActive: '#16a34a',
    colorSuccessText: '#16a34a',
    colorSuccessTextHover: '#22c55e',
    colorSuccessTextActive: '#15803d',
    colorWarningBg: '#fffbeb',
    colorWarningBgHover: '#fef3c7',
    colorWarningBorder: '#fde68a',
    colorWarningBorderHover: '#fcd34d',
    colorWarningHover: '#f59e0b',
    colorWarningActive: '#d97706',
    colorWarningText: '#d97706',
    colorWarningTextHover: '#f59e0b',
    colorWarningTextActive: '#b45309',
    colorErrorBg: '#fef2f2',
    colorErrorBgHover: '#fee2e2',
    colorErrorBorder: '#fecaca',
    colorErrorBorderHover: '#fca5a5',
    colorErrorHover: '#ef4444',
    colorErrorActive: '#dc2626',
    colorErrorText: '#dc2626',
    colorErrorTextHover: '#ef4444',
    colorErrorTextActive: '#b91c1c',
    colorInfoBg: '#eef2ff',
    colorInfoBgHover: '#dbe4ff',
    colorInfoBorder: '#bac8f3',
    colorInfoBorderHover: '#9bb0e6',
    colorInfoHover: '#3f6cb8',
    colorInfoActive: '#2e5aa8',
    colorInfoText: '#588ac9',
    colorInfoTextHover: '#3f6cb8',
    colorInfoTextActive: '#2e5aa8',
    colorText: '#334155',
    colorTextSecondary: '#64748b',
    colorTextTertiary: '#94a3b8',
    colorTextQuaternary: '#cbd5e1',
    colorTextDisabled: '#94a3b8',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#f8fafc',
    colorBgSpotlight: '#334155',
    colorBgMask: 'rgba(15, 23, 42, 0.6)',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#f1f5f9',
    borderRadius: 6,
    borderRadiusXS: 2,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    padding: 16,
    paddingSM: 12,
    paddingLG: 20,
    margin: 16,
    marginSM: 12,
    marginLG: 20,
    boxShadow:
      '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)',
    boxShadowSecondary:
      '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
  },
};
